# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: paulhatch/semantic-version@v5.0.2
        id: semver
        with:
          tag_prefix: "v"
          bump_each_commit: true
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver.outputs.version_tag }}",
              sha: context.sha
            })

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: docker.io/astromechza/ovo-energy-prometheus-gauge:${{ steps.semver.outputs.version_tag }}
